### ISSUE TITLE
Parsing fails with examples from HTTP Signature

### ISSUE THREAD

**Issue by DeGuitard** [Jxck/structured-field-values#1]
Hello,

I tried to use the library to parse an example given in HTTP Header "Signature-Input", from the [HTTP Signature](https://datatracker.ietf.org/doc/draft-ietf-httpbis-message-signatures/) latest draft:
```
   Signature-Input: sig1=(*request-target, *created, host, date,
       cache-control, x-empty-header, x-example); keyId="test-key-a";
       alg=hs2019; created=1402170695; expires=1402170995
```

Turns out the parsing fails. Here is the error output:
```
$ node index.js
/redacted/node_modules/structured-field-values/index.js:134
    throw new Error(`failed to parse: trailing values ${result.rest}`)
    ^

Error: failed to parse: trailing values =(*request-target, *created, host, date, cache-control, x-empty-header, x-example); keyId="test-key-a"; alg=hs2019; created=1402170695; expires=1402170995
    at Object.parseDict (/redacted/node_modules/structured-field-values/index.js:134:11)
    at Object.<anonymous> (/redacted/index.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
```

I found out by trial and error that two things are triggering this error:
- `keyId` should be lower case. Using `keyid` works. Because the character class of parameter key is `lcalpha`.
- Making the List an InnerList by replacing the `,` separator with ` ` separator. Not totally sure why? But I figure only InnerLists should be used inside a Dictionnary.

Am I by any chance correct in this analysis, or is it actually a bug in the parser? Meaning it would all of the examples of the HTTP Signature specifications are invalid?

I'm sorry to write an issue for something that could actually not be an issue in the parser. But I feel like you are more knowledgeable of the HTTP Structured Headers specifications, and thus more legitimate to actually dismiss the examples of the HTTP Signature draft.

Thanks for your time reading this.

**Comment by Jxck** [comment]
Hi @DeGuitard 

in my understanding, this example intends Dictionary and invalid.
according to https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-19

1. dict key should not be uppercase

so `keyId` should be `keyid`, `key_id` or `key-id`


```
   key           = ( lcalpha / "*" )
                   *( lcalpha / DIGIT / "_" / "-" / "." / "*" )
```

2. dict members are separated by `,` not `;`

```
   sf-dictionary  = dict-member *( OWS "," OWS dict-member )
```

3. inner list members are separated by space not `,`

```
 inner-list    = "(" *SP [ sf-item *( 1*SP sf-item ) *SP ] ")"
                   parameters
```

So I think this should be encoded like below.


```diff
- sig1=(*request-target, *created, host, date, cache-control, x-empty-header, x-example); keyId="test-key-a"; alg=hs2019; created=1402170695; expires=1402170995
+ sig1=(*request-target *created host date cache-control x-empty-header x-example), key_id="test-key-a", alg=hs2019, created=1402170695, expires=1402170995
```

in my implementation also works fine.

```js
console.log(parseDict('sig1=(*request-target *created host date cache-control x-empty-header x-example), key_id="test-key-a", alg=hs2019, created=1402170695, expires=1402170995'))
{
  sig1: {
    value: [
      { value: Symbol(*request-target), params: {} },
      { value: Symbol(*created), params: {} },
      { value: Symbol(host), params: {} },
      { value: Symbol(date), params: {} },
      { value: Symbol(cache-control), params: {} },
      { value: Symbol(x-empty-header), params: {} },
      { value: Symbol(x-example), params: {} }
    ],
    params: {}
  },
  key_id: { value: 'test-key-a', params: {} },
  alg: { value: Symbol(hs2019), params: {} },
  created: { value: 1402170695, params: {} },
  expires: { value: 1402170995, params: {} }
}
```

hope it helps you.

**Comment by DeGuitard** [comment]
Hello,

Thanks a lot for your answer. I agree with you, the example given in the latest HTTP Signature draft does seem wrong. I'm not really used to reading drafts from IETF, so maybe errors like these are common, I was just surprised that the specification of a field as important as keyId would not be compatible with the structures headers draft.

I went with an implementation similar to what you are suggesting. I do think though that the `;` usage in the dict is correct, as per my understand these are parameters of the inner list. Basically it could look like:
```
sig1=(*created, x-example); keyId="test-key-a"; alg=hs2019; created=1402170695, sig2=(*created, digest); keyId="test-key-b"; alg=hs2019; created=1402170695 
```

I'll try to send a message to the working group of the HTTP Signature through their mailing list.

**Comment by DeGuitard** [comment]
Note: I found a new version (published 4 days ago) that contains the aforementionned fixes
https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html

The new example:
```
Signature-Input: sig1=(*request-target *created host date
    cache-control x-empty-header x-example); keyid="test-key-a";
    alg=hs2019; created=1402170695; expires=1402170995
```
