### ISSUE TITLE
How do I serialize an inner list with parameters?

### ISSUE THREAD

**Issue by aljones15** [Jxck/structured-field-values#10]
If I make a dictionary with an inner list:

```js
sig1=("date" "multiple");keyid="foo";alg="bar"'
```
 if I try to serialize that one value in the dictionary I can't:

```js
const {sig1} = decodeDict('sig1=("date" "multiple");keyid="foo";alg="bar"');
encodeDict(sig1)
//      Error: failed to serialize [object Object] as Bare Item
encodeList(sig1)
//      Error: failed to serialize [object Object] as List
encodeList(sig1.value, sig1.params)
// serializes to a normal list with no params "date" "mutliple"
encodeItem(sig1)
// Error: failed to serialize [object Object],[object Object] as Bare Item
encodeItem(sig1.value, sig1.params)
//      Error: failed to serialize [object Object],[object Object] as Item
```

Support for inner lists is there, but an easy way to serialize them is not.

**Comment by Jxck** [comment]
decodeDict returns dictionary(js object) witch key is `sig1` but you destructuring it as `{sig1}`.
this case `sig1` is value of inner list with parameters.
inner list with params are not Dict, List and Item.
you can't encode it as valid sfv.

**Comment by Jxck** [comment]
reopen it if necessary.
