### ISSUE TITLE
Types seems off?

### ISSUE THREAD

**Issue by mitar** [Jxck/structured-field-values#15]
```ts
export function decodeDict(input: string): Dictionary;
export type Dictionary = any | Map<any, any>;
```

`any` there really prevents any type checking to happen.

I defined `type ItemTypes = BareItem | ItemTypes[]` and then I think `Dictionary` should be:

```ts
type Dictionary = Record<Key, ItemTypes> | Map<Key, ItemTypes>;
```

**Comment by Jxck** [comment]
It's been declared like below.

```js
/**
 * @typedef {Object.<Key, Item|InnerList>|Map} Dictionary
 */
```

but build results replaced by any

I digging here and found it caused by `Key` and replaced it with `string` seems workaround here.

```js
/**
 * @typedef {Object.<string, Item|InnerList>|Map} Dictionary
 */
```

so I'll partially apply it and will fix later.

Thanks
