### ISSUE TITLE
Please include a copy of MIT license in the repository

### ISSUE THREAD

**Issue by mitar** [Jxck/structured-field-values#16]
`package.json` says the code is MIT licensed, but the repository is missing a copy of the license. As such it is hard to satisfy MIT license conditions which require from me to include a copyright notice (which is otherwise found in the license file).

**Comment by Jxck** [comment]
added, thanks.

**Comment by mitar** [comment]
Thank you. I would appreciate a version bump as well to get the file in.

**Comment by Jxck** [comment]
done ! https://www.npmjs.com/package/structured-field-values/v/2.0.4

**Comment by mitar** [comment]
Thanks!
