### ISSUE TITLE
Decimal serialization

### ISSUE THREAD

**Issue by jkhales** [Jxck/structured-field-values#3]
This should also fail if `Math.round(value) < -999999999999`:
https://github.com/Jxck/structured-field-values/blob/master/index.js#L331

Also, `999999999999.1` fails to serialize, when it should pass:
```If input_decimal has more than 12 significant digits to the left  of the decimal point after rounding,```

**Comment by Jxck** [comment]
it's already fixed during update to v3
https://github.com/Jxck/structured-field-values/blob/54cfea375be670cfcb873b6c0c4c4fc57e642bc9/index.js#L423

thanks
